### ISSUE TITLE
update authentication redirect url for discord bot

### ISSUE THREAD

**Issue by JakeTrevor** [JARP-Inc/settle-up#9]

**Comment by JakeTrevor** [comment]
you need to add an additional url at `https://settle-up-web.vercel.app/` instead of localhost

**Comment by RoryMcDermid** [comment]
the redirect url is updated, but it refuses to sign in

**Comment by JakeTrevor** [comment]
It seems there was a combination of issues here, between incorrect config on vercel, discord and planetscale. However, everything is now set up correctly.
